name: Production build

on: [push]

env:
  NODE_OPTIONS: "--max_old_space_size=8048"

jobs:
  testbuild_on_linux:
    name: Testbuild on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Install dependencies
      run: npm install
    - name: Build on Linux
      run: npm run build:prod
  build_on_mac:
    name: Build on MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Install dependencies
      run: npm install
    - name: Build on MacOS
      run: npm run build
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        skip_build: true

  build_on_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Install dependencies
      run: npm install
    - name: Build on Linux
      run: npm run build
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        skip_build: true
 
  build_on_win:
    name: Build on Windows
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master  
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Install dependencies
      run: npm install
    - name: Build on Windows
      run: npm run build
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        skip_build: true